### ISSUE TITLE
Model file corrupt

### ISSUE THREAD

**Issue by rsingh2083** [NVIDIAAICITYCHALLENGE/2018AICITY_MCPRL#2]
model_10000.tar finishes download properly but while untaring it, gives error 

```
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

```

**Comment by jiayi-wei** [comment]
The 'tar' extension does not mean anything. Thus, you can just load it with torch.load in pytorch.
